package com.akgarg.whatsappuiclone.constants

enum class ApplicationLoggingConstants {

    SEND_OTP_FAILED,
    STORAGE_LOCATION,
    FIREBASE_IMAGE,
    PROFILE_NAME_CHANGED,
    RADIO_BUTTON_CLICK_CHANGE,
    SWITCH_BUTTON_TAPPED,
    FIREBASE_CHAT_MESSAGE_UPLOAD,
    PROFILE_FOUND,
    CONTACTS_TAG,
    SECURITY_LOGS,
    CHAT_DATA_CHANGED,
    FIREBASE_PROFILE_PICTURE_UPLOAD_FAIL

}